artifactRepositoryRef:
  # ConfigMap1
  artifact-repositories:
    annotations:
      workflows.argoproj.io/default-artifact-repository: default-v1-s3-artifact-repository
    # data 1
    default-v1-s3-artifact-repository:
      archiveLogs: true
      s3:
        bucket: my-bucket
        endpoint: minio:9000
        insecure: true
        accessKeySecret:
          name: my-minio-cred
          key: accesskey
        secretKeySecret:
          name: my-minio-cred
          key: secretkey
    # data 2
    oss-artifact-repository:
      archiveLogs: false
      oss:
        endpoint: http://oss-cn-zhangjiakou-internal.aliyuncs.com
        bucket: $mybucket
        accessKeySecret:
          name: $mybucket-credentials
          key: accessKey
        secretKeySecret:
          name: $mybucket-credentials
          key: secretKey
  # ConfigMap2
  another-artifact-repositories:
    annotations:
      workflows.argoproj.io/default-artifact-repository: gcs
    gcs:
      archiveLogs: false
      bucket: my-bucket
      keyFormat: prefix/in/bucket/{{workflow.name}}/{{pod.name}}
      serviceAccountKeySecret:
        name: my-gcs-credentials
        key: serviceAccountKey
